import React, { useState, useEffect, useMemo } from 'react';
import { 
  Layout, 
  Palette, 
  Type, 
  Box, 
  Download, 
  Settings,
  Loader2,
  ArrowRight,
  Code,
  FileJson,
  Check,
  Copy,
  Search,
  Zap,
  GitPullRequest,
  Monitor,
  Command,
  Info,
  Layers,
  Sparkles,
  FileText,
  FileCode,
  ExternalLink,
  Globe
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { jsPDF } from 'jspdf';
import { fetchFigmaFile, extractTokens, fetchFigmaImages } from './services/figma';

// Mock data for Demo Mode
const MOCK_TOKENS = {
  colors: [
    { name: 'Brand Primary', hex: '#A78BFA', r: 167, g: 139, b: 250 },
    { name: 'Brand Secondary', hex: '#22D3EE', r: 34, g: 211, b: 238 },
    { name: 'Bg App', hex: '#050505', r: 5, g: 5, b: 5 },
    { name: 'Bg Surface', hex: '#0F0F12', r: 15, g: 15, b: 18 },
    { name: 'Success', hex: '#34D399', r: 52, g: 211, b: 153 },
    { name: 'Warning', hex: '#FBBF24', r: 251, g: 191, b: 36 },
    { name: 'Error', hex: '#F87171', r: 248, g: 113, b: 113 },
  ],
  typography: [
    { name: 'Display XL', fontFamily: 'Outfit', fontSize: 64, fontWeight: 800 },
    { name: 'Heading L', fontFamily: 'Outfit', fontSize: 32, fontWeight: 700 },
    { name: 'Body M', fontFamily: 'Inter', fontSize: 16, fontWeight: 400 },
    { name: 'Mono Code', fontFamily: 'JetBrains Mono', fontSize: 14, fontWeight: 400 },
  ],
  components: [
    { id: '1', name: 'Primary Button', type: 'COMPONENT' },
    { id: '2', name: 'Nav Bar', type: 'COMPONENT' },
    { id: '3', name: 'Glass Card', type: 'COMPONENT' },
    { id: '4', name: 'Search Input', type: 'COMPONENT' },
  ],
  fileInfo: {
    name: 'Untitled Design System',
    lastModified: new Date().toISOString(),
    thumbnailUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=400'
  }
};

const App = () => {
  const [apiKey, setApiKey] = useState('');
  const [fileUrl, setFileUrl] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [tokens, setTokens] = useState(null);
  const [componentImages, setComponentImages] = useState({});
  const [activeTab, setActiveTab] = useState('overview');
  const [searchQuery, setSearchQuery] = useState('');
  const [copied, setCopied] = useState(false);

  const extractFileId = (url) => {
    const match = url.match(/(?:file|design)\/([a-zA-Z0-9]+)/);
    if (match) return match[1];
    if (/^[a-zA-Z0-9]+$/.test(url)) return url;
    return url;
  };

  const handleGenerate = async (e) => {
    if (e) e.preventDefault();
    setLoading(true);
    setError('');
    
    try {
      const fileId = extractFileId(fileUrl);
      const data = await fetchFigmaFile(fileId, apiKey);
      const extractedTokens = extractTokens(data);
      setTokens({
        ...extractedTokens,
        fileInfo: {
          name: data.name,
          lastModified: data.lastModified,
          thumbnailUrl: data.thumbnailUrl
        }
      });

      if (extractedTokens.components.length > 0) {
        const ids = extractedTokens.components.map(c => c.id).slice(0, 20);
        const images = await fetchFigmaImages(fileId, ids, apiKey);
        setComponentImages(images);
      }
    } catch (err) {
      setError('Invalid API Key or File URL. Please try again.');
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const startDemo = () => {
    setLoading(true);
    setTimeout(() => {
      setTokens(MOCK_TOKENS);
      setLoading(false);
    }, 1500);
  };

  const copyToClipboard = (text) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadMarkdown = () => {
    let content = `# Design System: ${tokens.fileInfo.name}\n\n`;
    content += `Generated by FigmaTokens Pro - Sangar Studio\n\n`;
    
    content += `## Colors\n\n`;
    tokens.colors.forEach(c => {
      content += `- **${c.name}**: ${c.hex} (RGB ${c.r}, ${c.g}, ${c.b})\n`;
    });

    content += `\n## Typography\n\n`;
    tokens.typography.forEach(t => {
      content += `- **${t.name}**: ${t.fontSize}px ${t.fontFamily} (Weight ${t.fontWeight})\n`;
    });

    content += `\n## Components\n\n`;
    tokens.components.forEach(c => {
      content += `- ${c.name} (${c.type})\n`;
    });

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'design.md';
    a.click();
  };

  const downloadPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(22);
    doc.text(`Design System: ${tokens.fileInfo.name}`, 10, 20);
    
    doc.setFontSize(12);
    doc.text(`Author: Sangar Studio (https://sangar.studio)`, 10, 30);
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 10, 35);
    
    let y = 50;
    doc.setFontSize(16);
    doc.text("Color Palette", 10, y);
    y += 10;
    doc.setFontSize(10);
    tokens.colors.forEach((c, i) => {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.text(`${c.name}: ${c.hex}`, 15, y);
      y += 7;
    });

    y += 10;
    doc.setFontSize(16);
    doc.text("Typography", 10, y);
    y += 10;
    doc.setFontSize(10);
    tokens.typography.forEach((t, i) => {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.text(`${t.name}: ${t.fontSize}px ${t.fontFamily}`, 15, y);
      y += 7;
    });

    doc.save('design.pdf');
  };

  const filteredItems = useMemo(() => {
    if (!tokens) return null;
    const query = searchQuery.toLowerCase();
    return {
      colors: tokens.colors.filter(c => c.name.toLowerCase().includes(query)),
      typography: tokens.typography.filter(t => t.name.toLowerCase().includes(query)),
      components: tokens.components.filter(c => c.name.toLowerCase().includes(query))
    };
  }, [tokens, searchQuery]);

  if (!tokens) {
    return (
      <div className="landing-page">
        <header className="landing-header">
          <div className="logo">
            <Sparkles className="icon-glow" color="var(--accent-primary)" size={32} />
            <span>FigmaTokens Pro</span>
          </div>
          <div className="header-links">
            <button className="btn-link" onClick={startDemo}>View Demo</button>
            <GitPullRequest size={20} className="text-dim hover:text-white cursor-pointer" />
          </div>
        </header>

        <main className="landing-hero">
          <motion.div 
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            className="hero-content"
          >
            <div className="badge-new">By Sangar Studio</div>
            <h1 className="gradient-title">Bridge the gap between <br/> Design & Code.</h1>
            <p className="hero-subtitle">
              The world's fastest way to extract design tokens from Figma. 
              Get production-ready CSS, JSON, and documentation in seconds.
            </p>

            <div className="setup-box card-premium animate-in">
              <form onSubmit={handleGenerate} className="setup-form">
                <div className="form-row">
                  <div className="input-wrap">
                    <label>Figma Personal Token</label>
                    <input 
                      type="password" 
                      placeholder="figd_..." 
                      className="input-premium"
                      value={apiKey}
                      onChange={(e) => setApiKey(e.target.value)}
                    />
                  </div>
                  <div className="input-wrap">
                    <label>File URL</label>
                    <input 
                      type="text" 
                      placeholder="figma.com/file/..." 
                      className="input-premium"
                      value={fileUrl}
                      onChange={(e) => setFileUrl(e.target.value)}
                    />
                  </div>
                </div>

                <div className="form-footer">
                  <button type="submit" className="btn-premium primary" disabled={loading || (!apiKey && !fileUrl)}>
                    {loading ? <Loader2 className="animate-spin" /> : <><Zap size={18} /> Generate System</>}
                  </button>
                  <div className="divider">or</div>
                  <button type="button" className="btn-premium" onClick={startDemo}>
                    Try with Demo Data
                  </button>
                </div>
                {error && <p className="error-text">{error}</p>}
              </form>
            </div>
          </motion.div>
        </main>

        <style>{`
          .landing-page {
            height: 100vh;
            background: var(--bg-app);
            overflow-y: auto;
            display: flex;
            flex-direction: column;
            background-image: 
              radial-gradient(circle at 50% -20%, rgba(167, 139, 250, 0.15) 0%, transparent 50%),
              url("https://www.transparenttextures.com/patterns/carbon-fibre.png");
          }
          .landing-header { display: flex; justify-content: space-between; align-items: center; padding: 2rem 4rem; }
          .logo { display: flex; align-items: center; gap: 1rem; font-family: var(--font-display); font-weight: 800; font-size: 1.5rem; }
          .icon-glow { filter: drop-shadow(0 0 8px var(--accent-glow)); }
          .landing-hero { flex: 1; display: flex; align-items: center; justify-content: center; padding: 4rem; }
          .hero-content { max-width: 900px; text-align: center; }
          .badge-new { display: inline-block; background: rgba(167, 139, 250, 0.1); color: var(--accent-primary); padding: 0.4rem 1rem; border-radius: 100px; font-size: 0.8rem; font-weight: 600; margin-bottom: 2rem; border: 1px solid rgba(167, 139, 250, 0.2); }
          .gradient-title { background: linear-gradient(to bottom, #fff, #999); -webkit-background-clip: text; -webkit-text-fill-color: transparent; margin-bottom: 2rem; }
          .hero-subtitle { font-size: 1.25rem; max-width: 600px; margin: 0 auto 3rem; }
          .setup-box { background: rgba(15, 15, 18, 0.8); backdrop-filter: blur(20px); padding: 3rem; text-align: left; border: 1px solid var(--bg-border); }
          .form-row { display: grid; grid-template-columns: 1fr 1fr; gap: 2rem; margin-bottom: 2rem; }
          .input-wrap label { display: block; font-size: 0.85rem; color: var(--text-dim); margin-bottom: 0.75rem; font-weight: 500; }
          .form-footer { display: flex; align-items: center; gap: 1.5rem; }
          .divider { color: var(--text-dim); font-size: 0.9rem; }
          .error-text { color: var(--error); margin-top: 1.5rem; font-size: 0.9rem; }
          .btn-link { color: var(--text-secondary); font-weight: 500; transition: color 0.2s; }
          .btn-link:hover { color: white; }
          .animate-spin { animation: spin 1s linear infinite; }
          @keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
        `}</style>
      </div>
    );
  }

  return (
    <div className="app-container">
      <aside className="app-sidebar glass-effect">
        <div className="sidebar-top">
          <div className="logo-small">
            <Sparkles size={24} color="var(--accent-primary)" />
            <span>FigmaTokens</span>
          </div>
          
          <nav className="side-nav">
            <NavItem active={activeTab === 'overview'} onClick={() => setActiveTab('overview')} icon={<Monitor size={18} />} label="Overview" />
            <NavItem active={activeTab === 'colors'} onClick={() => setActiveTab('colors')} icon={<Palette size={18} />} label="Colors" />
            <NavItem active={activeTab === 'typography'} onClick={() => setActiveTab('typography')} icon={<Type size={18} />} label="Typography" />
            <NavItem active={activeTab === 'components'} onClick={() => setActiveTab('components')} icon={<Layers size={18} />} label="Components" />
            <NavItem active={activeTab === 'export'} onClick={() => setActiveTab('export')} icon={<Download size={18} />} label="Export" />
          </nav>
        </div>

        <div className="sidebar-bottom">
          <a href="https://sangar.studio" target="_blank" rel="noreferrer" className="author-link">
            <Globe size={14} />
            <span>By Sangar Studio</span>
            <ExternalLink size={10} />
          </a>
          <div className="file-info-mini">
            <img src={tokens.fileInfo.thumbnailUrl} alt="File Thumb" className="thumb" />
            <div className="info">
              <span className="file-name">{tokens.fileInfo.name}</span>
              <span className="file-date">Last synced {new Date(tokens.fileInfo.lastModified).toLocaleDateString()}</span>
            </div>
          </div>
          <button className="btn-logout" onClick={() => setTokens(null)}>
            <Settings size={16} /> Change File
          </button>
        </div>
      </aside>

      <main className="app-content">
        <header className="content-nav">
          <div className="search-bar">
            <Search size={18} className="text-dim" />
            <input 
              type="text" 
              placeholder="Search design tokens..." 
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
            />
            <div className="kbd"><Command size={10} /> K</div>
          </div>
          <div className="nav-actions">
            <div className="user-badge">
              <div className="avatar">JD</div>
              <span>Admin</span>
            </div>
          </div>
        </header>

        <div className="scroll-area">
          <AnimatePresence mode="wait">
            <motion.div
              key={activeTab}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              transition={{ duration: 0.3 }}
              className="view-container"
            >
              {activeTab === 'overview' && (
                <div className="overview-grid">
                  <div className="hero-banner card-premium">
                    <div className="banner-text">
                      <h1>Welcome back!</h1>
                      <p>Your design system is up to date. We've detected {tokens.colors.length + tokens.typography.length + tokens.components.length} tokens in this file.</p>
                      <button className="btn-premium primary" onClick={() => setActiveTab('export')}>
                        Generate Code Package
                      </button>
                    </div>
                    <div className="banner-illus">
                      <Zap size={120} color="var(--accent-primary)" strokeWidth={0.5} />
                    </div>
                  </div>

                  <div className="stat-cards">
                    <StatCard icon={<Palette size={20} />} label="Colors" count={tokens.colors.length} color="#A78BFA" />
                    <StatCard icon={<Type size={20} />} label="Typography" count={tokens.typography.length} color="#22D3EE" />
                    <StatCard icon={<Layers size={20} />} label="Components" count={tokens.components.length} color="#34D399" />
                  </div>

                  <div className="recent-activity card-premium">
                    <h3>Design Health</h3>
                    <div className="health-meter">
                      <div className="meter-track">
                        <div className="meter-fill" style={{ width: '85%' }}></div>
                      </div>
                      <span>85% Consistent</span>
                    </div>
                    <p className="text-dim text-sm mt-2">3 typography styles are not linked to any document style.</p>
                  </div>
                </div>
              )}

              {activeTab === 'colors' && (
                <div className="token-view">
                  <div className="view-header">
                    <h2>Color Palette</h2>
                    <p>Global semantic colors and brand variables.</p>
                  </div>
                  <div className="token-grid">
                    {filteredItems.colors.map((color, i) => (
                      <ColorToken key={i} color={color} onCopy={copyToClipboard} />
                    ))}
                  </div>
                </div>
              )}

              {activeTab === 'typography' && (
                <div className="token-view">
                  <div className="view-header">
                    <h2>Type System</h2>
                    <p>Typography scales for different screen sizes.</p>
                  </div>
                  <div className="typo-list-premium">
                    {filteredItems.typography.map((typo, i) => (
                      <TypoToken key={i} typo={typo} />
                    ))}
                  </div>
                </div>
              )}

              {activeTab === 'components' && (
                <div className="token-view">
                  <div className="view-header">
                    <h2>Component Library</h2>
                    <p>Registered Figma components and interactive elements.</p>
                  </div>
                  <div className="comp-grid-premium">
                    {filteredItems.components.map((comp, i) => (
                      <CompToken key={i} comp={comp} imageUrl={componentImages[comp.id]} />
                    ))}
                  </div>
                </div>
              )}

              {activeTab === 'export' && (
                <div className="export-view">
                  <div className="view-header">
                    <div className="flex justify-between items-center w-full">
                      <div>
                        <h2>Export Tokens</h2>
                        <p>Download or copy your tokens in multiple formats.</p>
                      </div>
                      <div className="flex gap-2">
                        <button className="btn-premium" onClick={downloadMarkdown}>
                          <FileText size={16} /> design.md
                        </button>
                        <button className="btn-premium" onClick={downloadPDF}>
                          <FileCode size={16} /> design.pdf
                        </button>
                        <button className="btn-premium primary" onClick={() => copyToClipboard(JSON.stringify(tokens, null, 2))}>
                          <Zap size={16} /> Copy for Figma Plugin
                        </button>
                      </div>
                    </div>
                  </div>
                  <div className="export-options">
                    <ExportCard 
                      title="CSS Variables" 
                      lang="css"
                      code={`:root {\n${tokens.colors.map(c => `  --color-${c.name.toLowerCase().replace(/\s+/g, '-')}: ${c.hex};`).join('\n')}\n}`} 
                      onCopy={copyToClipboard}
                      copied={copied}
                    />
                    <ExportCard 
                      title="JSON Tokens" 
                      lang="json"
                      code={JSON.stringify(tokens, null, 2)} 
                      onCopy={copyToClipboard}
                      copied={copied}
                    />
                  </div>
                </div>
              )}
            </motion.div>
          </AnimatePresence>
        </div>
      </main>

      <style>{`
        .app-sidebar { width: 280px; display: flex; flex-direction: column; padding: 2rem 1.5rem; border-right: 1px solid var(--bg-border); justify-content: space-between; }
        .logo-small { display: flex; align-items: center; gap: 0.75rem; font-family: var(--font-display); font-weight: 800; font-size: 1.25rem; margin-bottom: 3rem; padding-left: 0.5rem; }
        .side-nav { display: flex; flex-direction: column; gap: 0.5rem; }
        .nav-item-btn { display: flex; align-items: center; gap: 1rem; padding: 0.85rem 1rem; border-radius: var(--radius-md); color: var(--text-secondary); font-weight: 500; transition: var(--transition-smooth); width: 100%; }
        .nav-item-btn:hover { background: rgba(255,255,255,0.05); color: white; }
        .nav-item-btn.active { background: rgba(167, 139, 250, 0.1); color: var(--accent-primary); border: 1px solid rgba(167, 139, 250, 0.1); }
        .author-link { 
          display: flex; align-items: center; gap: 0.5rem; color: var(--accent-secondary); 
          font-size: 0.75rem; font-weight: 600; margin-bottom: 1.5rem; padding-left: 0.5rem;
          transition: var(--transition-smooth); text-decoration: none;
        }
        .author-link:hover { opacity: 0.8; transform: translateX(4px); }
        .file-info-mini { display: flex; align-items: center; gap: 1rem; padding: 1rem; background: var(--bg-surface); border-radius: var(--radius-md); margin-bottom: 1rem; border: 1px solid var(--bg-border); }
        .file-info-mini .thumb { width: 32px; height: 32px; border-radius: 6px; object-fit: cover; }
        .file-info-mini .info { display: flex; flex-direction: column; overflow: hidden; }
        .file-name { font-size: 0.85rem; font-weight: 600; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
        .file-date { font-size: 0.7rem; color: var(--text-dim); }
        .btn-logout { display: flex; align-items: center; gap: 0.5rem; color: var(--text-dim); font-size: 0.85rem; padding-left: 1rem; transition: color 0.2s; }
        .btn-logout:hover { color: white; }
        .app-content { flex: 1; display: flex; flex-direction: column; overflow: hidden; }
        .content-nav { height: 80px; border-bottom: 1px solid var(--bg-border); display: flex; align-items: center; justify-content: space-between; padding: 0 4rem; }
        .search-bar { display: flex; align-items: center; gap: 1rem; background: var(--bg-surface); border: 1px solid var(--bg-border); padding: 0.6rem 1.25rem; border-radius: 100px; width: 400px; }
        .search-bar input { background: none; border: none; color: white; flex: 1; outline: none; font-size: 0.9rem; }
        .kbd { background: var(--bg-border); padding: 0.2rem 0.4rem; border-radius: 4px; color: var(--text-dim); font-size: 0.7rem; display: flex; align-items: center; gap: 2px; }
        .user-badge { display: flex; align-items: center; gap: 0.75rem; font-weight: 500; font-size: 0.9rem; }
        .avatar { width: 32px; height: 32px; background: linear-gradient(135deg, var(--accent-primary), var(--accent-secondary)); border-radius: 50%; display: flex; align-items: center; justify-content: center; color: #000; font-weight: 700; font-size: 0.7rem; }
        .scroll-area { flex: 1; overflow-y: auto; padding: 4rem; }
        .view-container { max-width: 1200px; margin: 0 auto; }
        .overview-grid { display: grid; grid-template-columns: 2fr 1fr; gap: 2rem; }
        .hero-banner { grid-column: span 2; display: flex; align-items: center; justify-content: space-between; padding: 3rem; background: linear-gradient(135deg, rgba(167, 139, 250, 0.1), transparent); border: 1px solid rgba(167, 139, 250, 0.2); }
        .banner-text h1 { margin-bottom: 1rem; }
        .banner-text p { margin-bottom: 2rem; font-size: 1.1rem; }
        .stat-cards { grid-column: 1; display: grid; grid-template-columns: repeat(3, 1fr); gap: 1.5rem; }
        .stat-card { background: var(--bg-surface); border: 1px solid var(--bg-border); border-radius: var(--radius-lg); padding: 1.5rem; }
        .stat-icon { width: 40px; height: 40px; border-radius: 10px; display: flex; align-items: center; justify-content: center; margin-bottom: 1.25rem; }
        .stat-label { color: var(--text-dim); font-size: 0.9rem; display: block; }
        .stat-count { font-size: 2rem; font-weight: 800; font-family: var(--font-display); }
        .recent-activity { grid-column: 2; display: flex; flex-direction: column; gap: 1rem; }
        .health-meter { margin-top: 1rem; display: flex; align-items: center; gap: 1rem; }
        .meter-track { flex: 1; height: 8px; background: var(--bg-border); border-radius: 10px; overflow: hidden; }
        .meter-fill { height: 100%; background: var(--success); }
        .token-view { display: flex; flex-direction: column; gap: 2rem; }
        .view-header h2 { font-size: 2.5rem; margin-bottom: 0.5rem; }
        .token-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap: 1.5rem; }
        .color-token-card { padding: 0; overflow: hidden; }
        .color-well { height: 140px; position: relative; cursor: pointer; }
        .color-copy-btn { position: absolute; top: 1rem; right: 1rem; opacity: 0; transition: 0.2s; }
        .color-well:hover .color-copy-btn { opacity: 1; }
        .color-details { padding: 1.25rem; }
        .color-meta { display: flex; justify-content: space-between; align-items: center; }
        .color-name { font-weight: 700; font-family: var(--font-display); }
        .color-hex { font-family: var(--font-mono); font-size: 0.8rem; color: var(--text-dim); }
        .typo-list-premium { display: flex; flex-direction: column; gap: 1rem; }
        .typo-row { padding: 1.5rem 2rem; display: flex; align-items: center; gap: 3rem; }
        .typo-meta-box { width: 250px; }
        .typo-meta-box .name { display: block; font-weight: 700; color: var(--accent-secondary); }
        .typo-meta-box .stats { font-size: 0.8rem; color: var(--text-dim); }
        .typo-prev { flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
        .comp-grid-premium { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 2rem; }
        .comp-card-premium { padding: 0; overflow: hidden; }
        .comp-hero { height: 180px; background: rgba(0,0,0,0.2); display: flex; align-items: center; justify-content: center; padding: 2rem; }
        .comp-hero img { max-width: 100%; max-height: 100%; object-fit: contain; filter: drop-shadow(0 4px 12px rgba(0,0,0,0.3)); }
        .comp-body { padding: 1.25rem; }
        .export-options { display: grid; grid-template-columns: 1fr 1fr; gap: 2rem; }
        .export-card-wrap { display: flex; flex-direction: column; gap: 1.5rem; }
        .code-container { background: #000; padding: 2rem; border-radius: var(--radius-md); height: 350px; overflow: auto; font-family: var(--font-mono); font-size: 0.85rem; color: #a5d6ff; line-height: 1.5; border: 1px solid var(--bg-border); }
        .flex { display: flex; }
        .flex-col { flex-direction: column; }
        .justify-between { justify-content: space-between; }
        .items-center { align-items: center; }
        .gap-2 { gap: 0.5rem; }
        .w-full { width: 100%; }
        .mb-4 { margin-bottom: 1rem; }
        .mt-2 { margin-top: 0.5rem; }
        .text-sm { font-size: 0.85rem; }
      `}</style>
    </div>
  );
};

const NavItem = ({ active, onClick, icon, label }) => (
  <button className={`nav-item-btn ${active ? 'active' : ''}`} onClick={onClick}>
    {icon} <span>{label}</span>
  </button>
);

const StatCard = ({ icon, label, count, color }) => (
  <div className="stat-card">
    <div className="stat-icon" style={{ background: `${color}15`, color }}>{icon}</div>
    <span className="stat-label">{label}</span>
    <span className="stat-count">{count}</span>
  </div>
);

const ColorToken = ({ color, onCopy }) => (
  <div className="color-token-card card-premium">
    <div className="color-well" style={{ background: color.hex }} onClick={() => onCopy(color.hex)}>
      <div className="color-copy-btn btn-premium glass-effect"><Copy size={12} /></div>
    </div>
    <div className="color-details">
      <div className="color-meta">
        <span className="color-name">{color.name}</span>
        <code className="color-hex">{color.hex}</code>
      </div>
      <div className="rgb-vals text-dim text-sm mt-2">RGB {color.r}, {color.g}, {color.b}</div>
    </div>
  </div>
);

const TypoToken = ({ typo }) => (
  <div className="typo-row card-premium">
    <div className="typo-meta-box">
      <span className="name">{typo.name}</span>
      <span className="stats">{typo.fontFamily} • {typo.fontSize}px • Weight {typo.fontWeight}</span>
    </div>
    <div className="typo-prev" style={{ fontFamily: typo.fontFamily, fontSize: Math.min(typo.fontSize, 32), fontWeight: typo.fontWeight }}>
      The quick brown fox jumps over the lazy dog.
    </div>
  </div>
);

const CompToken = ({ comp, imageUrl }) => (
  <div className="comp-card-premium card-premium">
    <div className="comp-hero">
      {imageUrl ? <img src={imageUrl} alt={comp.name} /> : <Box size={48} color="var(--text-dim)" />}
    </div>
    <div className="comp-body">
      <h3>{comp.name}</h3>
      <p className="text-sm text-dim">{comp.type}</p>
    </div>
  </div>
);

const ExportCard = ({ title, lang, code, onCopy, copied }) => (
  <div className="export-card-wrap card-premium">
    <div className="flex justify-between items-center mb-4">
      <h3>{title}</h3>
      <div className="badge-new">{lang.toUpperCase()}</div>
    </div>
    <div className="code-container"><pre><code>{code}</code></pre></div>
    <button className="btn-premium primary" onClick={() => onCopy(code)}>
      {copied ? <><Check size={18} /> Copied!</> : <><Copy size={18} /> Copy {lang.toUpperCase()}</>}
    </button>
  </div>
);

export default App;
